apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-microservice
  labels:
    app: users-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-microservice
  template:
    metadata:
      labels:
        app: users-microservice
    spec:
      containers:
      - name: users-microservice
        image: josemarcial1311/users_microservice
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /api/v0
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
